# Generated by Django 6.0.6 on 2026-07-08 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('departments', '0002_businessunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_unit',
            field=models.ForeignKey(blank=True, help_text="The employee's own team, e.g. Sales, Marketing (informational only).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='departments.businessunit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='The support team this staff member belongs to (managers/agents only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='departments.department'),
        ),
    ]
